---
name: Ansible Linting Action
description: Action to run Ansible lint.
author: L3D <l3d@c3woc.de>

inputs:
  target:
    description: |
      Target for ansible linter
      For example './', 'roles/my_role/' or 'site.yml'
    required: true
  required_collections:
    description: |
      You can define a required ansible collection here.
      They will be installed using ansible-galaxy collection install <YourInput> --upgrade.
    required: false
  collections_yml:
    description: |
      Install multiple Collections, defined from requirements.yml file
      They will be installed using ansible-galaxy collection install -r <YourInput> --upgrade.
    required: false
  required_roles:
    description: |
      You can define a required ansible role here.
      They will be installed using ansible-galaxy role install <YourInput> --upgrade.
    required: false
  python_dependency:
    description: |
      Install a Python Package using pip
      They will be installed using pip install --upgrade <YourInput>.
    required: false
  python_dependency_file:
    description: |
      Install a Python Packages from file using pip
      They will be installed using pip install --upgrade -r <YourInput>.
    required: false
runs:
  using: docker
  image: Dockerfile
  env:
    TARGET: ${{ inputs.target }}
    REQCOLLECTIONS: ${{ inputs.required_collections }}
    COLLECTIONSYML: ${{ inputs.collections_yml }}
    REQROLES: ${{ inputs.required_roles }}
    PIPPACKAGE: ${{ inputs.python_dependency }}
    PIPPACKAGETXT: ${{ inputs.python_dependency_file }}
branding:
  icon: 'check-circle'
  color: 'blue'
